name: deploy-toy-website-test
concurrency:
    group: thEdenBbay
    cancel-in-progress: false
on: workflow_dispatch
permissions:
    id-token: write
    contents: read
env:
    AZURE_RESOURCEGROUP_NAME: TheEdenBaby
    ENVIRONMENT_TYPE: Test
defaults:
  run:
      shell: pwsh
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout under $GITHUB_WORKSPACE
          uses: actions/checkout@v4.1.1
        - name: Run Bicep linter
          run: az bicep build --file deploy/main.bicep
    validate:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout under $GITHUB_WORKSPACE
          uses: actions/checkout@v4.1.1
        - name: Login to Azure
          uses: Azure/login@v1.6.1
          with:
            client-id: ${{ vars.AZURE_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID }}
            subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true
        - name: Run preflight validation
          env:
            AZURE_RESOURCEGROUP_NAME: ${{ env.AZURE_RESOURCEGROUP_NAME }}
            ENVIRONMENT: ${{ env.ENVIRONMENT_TYPE }}
          run: |
            $ErrorActionPreference = 'Stop'
            Set-StrictMode -Version 3
            $InformationPreference = 'Continue'

            Write-Information 'Install modules'
            Install-Module -Name 'Az.Resources' -Force

            $param = @{
                Mode = 'Complete'
                TemplateFile = 'deploy/main.bicep'
                SkipTemplateParameterPrompt = $true
                TemplateParameterObject = @{
                    environmentType = $env:ENVIRONMENT_TYPE
                }
            }

            $errorArray = Test-AzResourceGroupDeployment @param -ResourceGroupName $env:AZURE_RESOURCEGROUP_NAME

            $resultMessage = "There are [$('{0:N0}' -f $errorArray.count)] errors)"
            if ($errorArray.count -ne 0)
            {
              throw $resultMessage
            }
            else
            {
              write-information $resultMessage
            }
    deploy:
        runs-on: ubuntu-latest
        needs: [lint, validate]
        steps:
        - name: Checkout under $GITHUB_WORKSPACE
          uses: actions/checkout@v4.1.1
        - name: Login to Azure
          uses: Azure/login@v1.6.1
          with:
            client-id: ${{ vars.AZURE_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID }}
            subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true
        - name: Deploy to Azure
          env:
            AZURE_RESOURCEGROUP_NAME: ${{ env.AZURE_RESOURCEGROUP_NAME }}
            ENVIRONMENT: ${{ env.ENVIRONMENT_TYPE }}
          run: |
            $ErrorActionPreference = 'Stop'
            Set-StrictMode -Version 3
            $InformationPreference = 'Continue'

            Write-Information 'Install modules'
            Install-Module -Name 'Az.Resources' -Force

            $param = @{
                Name = 'edenStack'
                DeleteAll = $true
                Force = $true
                # TemplateFile = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath 'deploy' -AdditionalChildPath @('main.bicep')
                TemplateFile = 'deploy/main.bicep'
                DenySettingsMode = 'none'
                SkipTemplateParameterPrompt = $true
                TemplateParameterObject = @{
                    environmentType = $env:ENVIRONMENT_TYPE
                }
            }

            New-AzResourceGroupDeploymentStack @param -ResourceGroupName $env:AZURE_RESOURCEGROUP_NAME
        
        
        
